"""Глобальные константы проекта."""

# users
STR_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254

# tags
TAG_NAME_MAX_LENGTH = 32
SLUG_MAX_LENGTH = 32

# recipes/content
RECIPE_NAME_MAX_LENGTH = 256

# ingredients
INGREDIENT_NAME_MAX_LENGTH = 128
MEASUREMENT_UNIT_MAX_LENGTH = 64

# string representation helper
STR_REPRESENTATION_MAX_LENGTH = 20

# validation/min-values
MIN_COOKING_TIME_MINUTES = 1
MIN_INGREDIENT_AMOUNT = 1

# pagination
DEFAULT_PAGE_SIZE = 6
MAX_PAGE_SIZE = 100

# admin/configuration
ADMIN_INGREDIENT_INLINE_EXTRA = 0
ADMIN_INGREDIENT_INLINE_MIN_NUM = 1
ADMIN_RECIPE_IMAGE_WIDTH = 80
ADMIN_RECIPE_IMAGE_HEIGHT = 60

# recipes/cooking time thresholds (minutes)
COOKING_TIME_FAST_MAX = 20
COOKING_TIME_MEDIUM_MIN = 20
COOKING_TIME_MEDIUM_MAX = 60
COOKING_TIME_LONG_THRESHOLD = 60
